### ISSUE TITLE
jdbi dbi.open() does not seem to work on 1.0.0.CR8

### ISSUE THREAD

**Issue by kometen** [jooby-project/jooby#520]
Hi. 

I followed the restful-jdbi guide (https://github.com/jooby-guides/restful-jdbi) and had an error on dbi.open(). When I changed the version in pom.xml to 0.13.1 it would recognize dbi.open.

        use(new Jdbi().doWith((dbi, conf) -> {
            try (Handle h = dbi.open()) {
                h.execute(conf.getString("schema"));
            }
        }));

cannot find symbol
 symbol: method open()
 location: variable dbi of type Object

This is on macOS Sierra with JDK 1.8 update 111 and netbeans 8.2.

Regards
Claus

**Comment by jknack** [comment]
Hi @kometen, sorry need to update the guides to latest release.

For jdbi, you need to specify the type:

```java
    use(new Jdbi().doWith((DBI dbi, Config conf) -> {
        try (Handle h = dbi.open()) {
            h.execute(conf.getString("schema"));
        }
    }));
```

This was required to allow user to configure (or get early access to Datasource)

```java
    use(new Jdbi().doWith((Datasource ds, Config conf) -> {
     ...
    }));
```

The same: `doWith` callback let you tweak/acess to `DBI` or `Datasource` (from jdbc module)

While update guides soon.

Thanks

**Comment by jknack** [comment]
and of course you can do it `onStart` too:

```java
{
   onStart(registry -> {
      DBI dbi = registry.require(DBI.class);
      Config conf = registry.require(Config.class);
      try (Handle h = dbi.open()) {
        h.execute(conf.getString("schema"));
      }
   });
}
```

**Comment by kometen** [comment]
Thank you so much for the quick reply. It works and when you cast to DBI and Config it is quite obvious it should be solved this way. :-) Jooby is such a pleasure to work with. If I can help writing docs or other tasks I would like to give a hand.

**Comment by jknack** [comment]
Glad you like it! Your help with documentation, blog or tweet about jooby is very welcome!!!

**Comment by kometen** [comment]
I can have a look at the jdbi-rest-guide and make the necessary changes.

**Comment by jknack** [comment]
awesome! will let that to you

thanks

**Comment by kometen** [comment]
Hi Edgar. :-)

I wrote a simple rest-based service using hibernate and postgresql. It imports a file with cities and latitude/longitude and I link to the file from my dropbox-account. The file has slightly more than 3 mill. records. You can find the repo at https://github.com/kometen/jooby-worldcities.

Hope the code is readable.

regards
Claus
