### ISSUE TITLE
Question: Upgrade from 1.6.0 to 1.6.4 with classnotfound from hibernate 

### ISSUE THREAD

**Issue by martinbe1io** [jooby-project/jooby#1403]
Hi, 
 
up to Jooby 1.6.0 everything worked fine. after upgrade my pom to 1.6.4 I get a classnotfound problem from hibernate
 

```
log4j:WARN No appenders could be found for logger (org.jboss.logging).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Okt. 12, 2019 7:42:53 NACHM. com.google.inject.internal.MessageProcessor visit
INFORMATION: An exception was caught and reported. Message: java.lang.NoSuchMethodError: net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.isAvailable()Z
org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
       at io.be1.circular.my-app//org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:123)
       at io.be1.circular.my-app//org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:77)
       at io.be1.circular.my-app//org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:154)
       at io.be1.circular.my-app//org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:295)
       at io.be1.circular.my-app//org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:467)
       at io.be1.circular.my-app//org.jooby.hbm.Hbm.configure(Hbm.java:794)
       at io.be1.circular.my-app//org.jooby.Jooby.install(Jooby.java:3425)
       at io.be1.circular.my-app//org.jooby.Jooby.lambda$bindService$47(Jooby.java:3083)
       at io.be1.circular.my-app//org.jooby.funzy.Throwing$Consumer.lambda$accept$0(Throwing.java:273)
       at io.be1.circular.my-app//org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
       at io.be1.circular.my-app//org.jooby.funzy.Throwing.access$000(Throwing.java:39)
       at io.be1.circular.my-app//org.jooby.funzy.Throwing$Consumer.accept(Throwing.java:273)
       at io.be1.circular.my-app//org.jooby.Jooby.lambda$null$41(Jooby.java:2932)
       at io.be1.circular.my-app//org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
       at io.be1.circular.my-app//org.jooby.funzy.Throwing.access$000(Throwing.java:39)
       at io.be1.circular.my-app//org.jooby.funzy.Throwing$Runnable.run(Throwing.java:86)
       at io.be1.circular.my-app//org.jooby.funzy.Try.run(Try.java:729)
       at io.be1.circular.my-app//org.jooby.Jooby.lambda$bootstrap$44(Jooby.java:2918)
       at io.be1.circular.my-app//com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
       at io.be1.circular.my-app//com.google.inject.spi.Elements.getElements(Elements.java:103)
       at io.be1.circular.my-app//com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
       at io.be1.circular.my-app//com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
       at io.be1.circular.my-app//com.google.inject.Guice.createInjector(Guice.java:87)
       at io.be1.circular.my-app//com.google.inject.Guice.createInjector(Guice.java:78)
       at io.be1.circular.my-app//org.jooby.Jooby.lambda$new$0(Jooby.java:885)
       at io.be1.circular.my-app//org.jooby.Jooby.bootstrap(Jooby.java:2996)
       at io.be1.circular.my-app//org.jooby.Jooby.start(Jooby.java:2197)
       at io.be1.circular.my-app//org.jooby.Jooby.start(Jooby.java:2178)
       at io.be1.circular.my-app//org.jooby.Jooby.run(Jooby.java:2107)
       at io.be1.circular.my-app//io.be1.circular.App.main(App.java:577)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:564)
       at org.jooby.run.Main.lambda$startApp$3(Main.java:444)
       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
       at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.hibernate.HibernateException: Unable to instantiate default tuplizer [org.hibernate.tuple.entity.PojoEntityTuplizer]
       at io.be1.circular.my-app//org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:91)
       at io.be1.circular.my-app//org.hibernate.tuple.entity.EntityTuplizerFactory.constructDefaultTuplizer(EntityTuplizerFactory.java:116)
       at io.be1.circular.my-app//org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:382)
       at io.be1.circular.my-app//org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:554)
       at io.be1.circular.my-app//org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:124)
       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
       at io.be1.circular.my-app//org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:96)
       ... 39 more
Caused by: java.lang.reflect.InvocationTargetException
       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
       at io.be1.circular.my-app//org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:88)
       ... 48 more
Caused by: java.lang.IllegalArgumentException: Could not create type
       at io.be1.circular.my-app//net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:140)
       at io.be1.circular.my-app//net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:346)
       at io.be1.circular.my-app//net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:161)
       at io.be1.circular.my-app//net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:355)
       at io.be1.circular.my-app//org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.load(ByteBuddyState.java:183)
       at io.be1.circular.my-app//org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.loadProxy(ByteBuddyState.java:107)
       at io.be1.circular.my-app//org.hibernate.proxy.pojo.bytebuddy.ByteBuddyProxyHelper.buildProxy(ByteBuddyProxyHelper.java:54)
       at io.be1.circular.my-app//org.hibernate.proxy.pojo.bytebuddy.ByteBuddyProxyFactory.postInstantiate(ByteBuddyProxyFactory.java:62)
       at io.be1.circular.my-app//org.hibernate.tuple.entity.PojoEntityTuplizer.buildProxyFactory(PojoEntityTuplizer.java:162)
       at io.be1.circular.my-app//org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:156)
       at io.be1.circular.my-app//org.hibernate.tuple.entity.PojoEntityTuplizer.<init>(PojoEntityTuplizer.java:58)
       ... 53 more
Caused by: java.lang.NoSuchMethodError: net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.isAvailable()Z
       at io.be1.circular.my-app//org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.resolveClassLoadingStrategy(ByteBuddyState.java:229)
       at io.be1.circular.my-app//org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.lambda$load$0(ByteBuddyState.java:187)
       at io.be1.circular.my-app//net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:138)
       ... 63 more
 
```
 
I seems to be an incompatibility issue of hibernate, I found this post
 
https://stackoverflow.com/questions/53137982/hibernate-nosuchmethoderror-in-byte-buddy-when-building-session-factory
 
and extended my pom to use the new byte buddy library, with success my app starts again 
 
```
<dependency>
    <groupId>net.bytebuddy</groupId>
    <artifactId>byte-buddy</artifactId>
    <version>1.8.17</version>
</dependency>
```
 
unfortunately every database access leads to an exception with message "null". 
 
any idea what's wrong? using java 10.2 on Mac. 
 
Martin

**Comment by martinbe1io** [comment]
Was a dependency conflict, After Analysis with maven enforcer Plugin and elemination of the relevant issues all ok
